import { Zone } from "@prisma/client";

export type EntreeMappingDirect = {
    nom: string;
    lien_rss: string;
    categorie?: string;
    zone?: Zone;
};

export const DIRECT_RSS_MAPPING: Record<string, EntreeMappingDirect> = {
    "rfi.fr": { nom: "RFI - Monde", lien_rss: "https://www.rfi.fr/fr/rss", zone: Zone.international },
    "rfi.fr/afrique": { nom: "RFI - Afrique", lien_rss: "https://www.rfi.fr/fr/afrique/rss", zone: Zone.afrique },
    "rfi.fr/ameriques": { nom: "RFI - Amériques", lien_rss: "https://www.rfi.fr/fr/am%C3%A9riques/rss", zone: Zone.amerique },
    "rfi.fr/asie-pacifique": { nom: "RFI - Asie-Pacifique", lien_rss: "https://www.rfi.fr/fr/asie-pacifique/rss", zone: Zone.asie },
    "rfi.fr/europe": { nom: "RFI - Europe", lien_rss: "https://www.rfi.fr/fr/europe/rss", zone: Zone.europe },
    "rfi.fr/moyen-orient": { nom: "RFI - Moyen-Orient", lien_rss: "https://www.rfi.fr/fr/moyen-orient/rss", zone: Zone.international },
    "rfi.fr/economie": { nom: "RFI - Économie", lien_rss: "https://www.rfi.fr/fr/%C3%A9conomie/rss", categorie: "economie", zone: Zone.international },
    "rfi.fr/sports": { nom: "RFI - Sports", lien_rss: "https://www.rfi.fr/fr/sports/rss", categorie: "sport", zone: Zone.international },
    "rfi.fr/culture": { nom: "RFI - Culture", lien_rss: "https://www.rfi.fr/fr/culture/rss", zone: Zone.international },
    "rfi.fr/science": { nom: "RFI - Science & Environnement", lien_rss: "https://www.rfi.fr/fr/science/rss", categorie: "technologie", zone: Zone.international },

    // RFI Éditions Linguistiques
    "hausa.rfi.fr": { nom: "RFI Hausa", lien_rss: "https://www.rfi.fr/ha/rss", categorie: "international", zone: Zone.afrique },
    "swahili.rfi.fr": { nom: "RFI Swahili", lien_rss: "https://www.rfi.fr/sw/rss", categorie: "international", zone: Zone.afrique },
    "fulfulde.rfi.fr": { nom: "RFI Fulfulde", lien_rss: "https://www.rfi.fr/ff/rss", categorie: "international", zone: Zone.afrique },
    "mandenkan.rfi.fr": { nom: "RFI Mandenkan", lien_rss: "https://www.rfi.fr/bm/rss", categorie: "international", zone: Zone.afrique },
    "english.rfi.fr": { nom: "RFI English", lien_rss: "https://www.rfi.fr/en/rss", categorie: "international", zone: Zone.international },
    "espanol.rfi.fr": { nom: "RFI Español", lien_rss: "https://www.rfi.fr/es/rss", categorie: "international", zone: Zone.amerique },
    "portugues.rfi.fr": { nom: "RFI Português", lien_rss: "https://www.rfi.fr/pt/rss", categorie: "international", zone: Zone.international },
    "romanian.rfi.fr": { nom: "RFI România", lien_rss: "https://www.rfi.ro/rss", categorie: "international", zone: Zone.europe },
    "russian.rfi.fr": { nom: "RFI Russian", lien_rss: "https://www.rfi.fr/ru/rss", categorie: "international", zone: Zone.europe },
    "ukrainian.rfi.fr": { nom: "RFI Ukrainian", lien_rss: "https://www.rfi.fr/uk/rss", categorie: "international", zone: Zone.europe },
    "vietnamese.rfi.fr": { nom: "RFI Vietnamese", lien_rss: "https://www.rfi.fr/vi/rss", categorie: "international", zone: Zone.asie },
    "chinese.rfi.fr": { nom: "RFI Chinese", lien_rss: "https://www.rfi.fr/cn/rss", categorie: "international", zone: Zone.asie },

    "france24.com": { nom: "France 24 - À la une", lien_rss: "https://www.france24.com/fr/rss", categorie: "international", zone: Zone.international },
    "france24.com/afrique": { nom: "France 24 - Afrique", lien_rss: "https://www.france24.com/fr/afrique/rss", categorie: "international", zone: Zone.afrique },
    "france24.com/en": { nom: "France 24 - English", lien_rss: "https://www.france24.com/en/rss", categorie: "international", zone: Zone.international },
    "france24.com/monde": { nom: "France 24 - Monde", lien_rss: "https://www.france24.com/fr/monde/rss", categorie: "international", zone: Zone.international },
    "france24.com/eco": { nom: "France 24 - Économie", lien_rss: "https://www.france24.com/fr/%C3%A9co/rss", categorie: "economie", zone: Zone.international },
    "france24.com/france": { nom: "France 24 - France", lien_rss: "https://www.france24.com/fr/france/rss", categorie: "international", zone: Zone.europe },
    "france24.com/culture": { nom: "France 24 - Culture", lien_rss: "https://www.france24.com/fr/culture/rss", categorie: "culture", zone: Zone.international },
    "france24.com/sports": { nom: "France 24 - Sports", lien_rss: "https://www.france24.com/fr/sports/rss", categorie: "sport", zone: Zone.international },
    "france24.com/decouvertes": { nom: "France 24 - Découvertes", lien_rss: "https://www.france24.com/fr/d%C3%A9couvertes/rss", categorie: "culture", zone: Zone.international },
    "france24.com/moyen-orient": { nom: "France 24 - Moyen-Orient", lien_rss: "https://www.france24.com/fr/moyen-orient/rss", categorie: "international", zone: Zone.international },
    "france24.com/ameriques": { nom: "France 24 - Amériques", lien_rss: "https://www.france24.com/fr/am%C3%A9riques/rss", categorie: "international", zone: Zone.amerique },
    "france24.com/europe": { nom: "France 24 - Europe", lien_rss: "https://www.france24.com/fr/europe/rss", categorie: "international", zone: Zone.europe },
    "france24.com/asie-pacifique": { nom: "France 24 - Asie", lien_rss: "https://www.france24.com/fr/asie-pacifique/rss", categorie: "international", zone: Zone.asie },

    // France 24 Émissions
    "france24.com/le-debat": { nom: "France 24 - Émission - Le Débat", lien_rss: "https://www.france24.com/fr/%C3%A9missions/le-d%C3%A9bat/rss", categorie: "international", zone: Zone.international },
    "france24.com/les-observateurs": { nom: "France 24 - Émission - Les Observateurs", lien_rss: "https://www.france24.com/fr/%C3%A9missions/les-observateurs/rss", categorie: "international", zone: Zone.international },
    "france24.com/intelligence-economique": { nom: "France 24 - Émission - Intelligence Économique", lien_rss: "https://www.france24.com/fr/%C3%A9missions/intelligence-%C3%A9conomique/rss", categorie: "economie", zone: Zone.international },
    "france24.com/element-terre": { nom: "France 24 - Émission - Élément Terre", lien_rss: "https://www.france24.com/fr/%C3%A9missions/%C3%A9l%C3%A9ment-terre/rss", categorie: "international", zone: Zone.international },
    "france24.com/reporter": { nom: "France 24 - Émission - Reporter", lien_rss: "https://www.france24.com/fr/%C3%A9missions/reporter/rss", categorie: "international", zone: Zone.international },
    "france24.com/une-semaine-dans-le-monde": { nom: "France 24 - Émission - Une semaine dans le monde", lien_rss: "https://www.france24.com/fr/%C3%A9missions/une-semaine-dans-le-monde/rss", categorie: "international", zone: Zone.international },

    "lemonde.fr": { nom: "Le Monde.fr - Une", lien_rss: "https://www.lemonde.fr/rss/une.xml", categorie: "international", zone: Zone.europe },
    "mediapart.fr": { nom: "Mediapart", lien_rss: "https://www.mediapart.fr/articles/feed", categorie: "international", zone: Zone.europe },
    "nouvelobs.com": { nom: "L'Obs", lien_rss: "https://www.nouvelobs.com/a-la-une/rss.xml", categorie: "international", zone: Zone.europe },
    "francetvinfo.fr": { nom: "Franceinfo", lien_rss: "https://www.francetvinfo.fr/titres.rss", categorie: "international", zone: Zone.europe },
    "ouest-france.fr": { nom: "Ouest-France", lien_rss: "https://www.ouest-france.fr/rss-en-continu.xml", categorie: "international", zone: Zone.europe },
    "ladepeche.fr": { nom: "La Dépêche du Midi", lien_rss: "https://www.ladepeche.fr/rss.xml", categorie: "international", zone: Zone.europe },
    "lefigaro": { nom: "Le Figaro", lien_rss: "https://www.lefigaro.fr/rss/figaro_actualites.xml", categorie: "international", zone: Zone.europe },
    "liberation": { nom: "Libération", lien_rss: "https://www.liberation.fr/arc/outboundfeeds/rss-all/", categorie: "international", zone: Zone.europe },
    "les echos": { nom: "Les Echos", lien_rss: "https://lesechos.fr/rss/rss_une.xml", categorie: "international", zone: Zone.europe },
    "la tribune": { nom: "La Tribune", lien_rss: "https://www.latribune.fr/feed.xml", categorie: "international", zone: Zone.europe },
    "lexpress": { nom: "L'Express", lien_rss: "https://www.lexpress.fr/rss/alaune.xml", categorie: "international", zone: Zone.europe },
    "lobs": { nom: "L'Obs", lien_rss: "https://www.nouvelobs.com/rss.xml", categorie: "international", zone: Zone.europe },
    "mediapart": { nom: "Mediapart", lien_rss: "https://www.mediapart.fr/articles/feed", categorie: "international", zone: Zone.europe },
    "le point": { nom: "Le Point", lien_rss: "https://www.lepoint.fr/rss.xml", categorie: "international", zone: Zone.europe },
    "marianne": { nom: "Marianne", lien_rss: "https://www.marianne.net/rss.xml", categorie: "international", zone: Zone.europe },
    "20 minutes fr": { nom: "20 Minutes", lien_rss: "https://www.20minutes.fr/rss/une.xml", categorie: "international", zone: Zone.europe },
    "le parisien": { nom: "Le Parisien", lien_rss: "https://www.leparisien.fr/rss.xml", categorie: "international", zone: Zone.europe },
    "zeit.de": { nom: "ZEIT ONLINE", lien_rss: "http://newsfeed.zeit.de/index", categorie: "international", zone: Zone.europe },
    "faz.net": { nom: "FAZ.NET", lien_rss: "https://www.faz.net/rss/aktuell/", categorie: "international", zone: Zone.europe },
    "tagesschau.de": { nom: "tagesschau.de", lien_rss: "http://www.tagesschau.de/xml/rss2", categorie: "international", zone: Zone.europe },
    "dw.com": { nom: "Deutsche Welle", lien_rss: "https://rss.dw.com/rdf/rss-en-all", categorie: "international", zone: Zone.europe },
    "elpais.com": { nom: "EL PAÍS", lien_rss: "https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/portada", categorie: "international", zone: Zone.europe },
    "eldiario.es": { nom: "ElDiario.es", lien_rss: "https://www.eldiario.es/rss/", categorie: "international", zone: Zone.europe },
    "ansa.it": { nom: "ANSA.it", lien_rss: "https://www.ansa.it/sito/ansait_rss.xml", categorie: "international", zone: Zone.europe },
    "repubblica.it": { nom: "Repubblica.it", lien_rss: "https://www.repubblica.it/rss/homepage/rss2.0.xml", categorie: "international", zone: Zone.europe },
    "ilpost.it": { nom: "Il Post", lien_rss: "https://www.ilpost.it/feed/", categorie: "international", zone: Zone.europe },
    "rt.com": { nom: "RT", lien_rss: "https://www.rt.com/rss/", categorie: "international", zone: Zone.europe },
    "tass.com": { nom: "TASS", lien_rss: "http://tass.com/rss/v2.xml", categorie: "international", zone: Zone.europe },
    "themoscowtimes.com": { nom: "The Moscow Times", lien_rss: "https://www.themoscowtimes.com/rss/news", categorie: "international", zone: Zone.europe },
    "meduza.io": { nom: "Meduza.io", lien_rss: "https://meduza.io/rss/all", categorie: "international", zone: Zone.europe },
    "pravda.com.ua": { nom: "Ukrainska Pravda", lien_rss: "https://www.pravda.com.ua/rss/", categorie: "international", zone: Zone.europe },

    "bbc.com": { nom: "BBC World News", lien_rss: "https://feeds.bbci.co.uk/news/world/rss.xml", categorie: "international", zone: Zone.international },
    "bbc.co.uk": { nom: "BBC News Home", lien_rss: "http://feeds.bbci.co.uk/news/rss.xml", categorie: "international", zone: Zone.europe },
    "theguardian.com": { nom: "The Guardian World", lien_rss: "https://www.theguardian.com/world/rss", categorie: "international", zone: Zone.europe },
    "independent.co.uk": { nom: "The Independent UK", lien_rss: "http://www.independent.co.uk/news/uk/rss", categorie: "international", zone: Zone.europe },
    "dailymail.co.uk": { nom: "Daily Mail", lien_rss: "https://www.dailymail.co.uk/home/index.rss", categorie: "international", zone: Zone.europe },

    "cameroon-tribune.cm": { nom: "Cameroon Tribune", lien_rss: "https://www.cameroon-tribune.cm/feed.xml", categorie: "politique", zone: Zone.afrique },
    "journalducameroun.com": { nom: "Journal du Cameroun", lien_rss: "https://www.journalducameroun.com/feed/", categorie: "generale", zone: Zone.afrique },
    "actucameroun.com": { nom: "Actu Cameroun", lien_rss: "https://actucameroun.com/feed/", categorie: "generale", zone: Zone.afrique },
    "cameroon-info.net": { nom: "Cameroon Info Net", lien_rss: "https://www.cameroon-info.net/rss.xml", categorie: "generale", zone: Zone.afrique },
    "ecomatin.net": { nom: "EcoMatin", lien_rss: "https://ecomatin.net/feed/", categorie: "economie", zone: Zone.afrique },
    "investiraucameroun.com": { nom: "Investir au Cameroun", lien_rss: "https://www.investiraucameroun.com/rss.xml", categorie: "economie", zone: Zone.afrique },
    "quotidienmutations.info": { nom: "Mutations", lien_rss: "https://quotidienmutations.info/feed/", categorie: "generale", zone: Zone.afrique },
    "237online.com": { nom: "237Online", lien_rss: "https://237online.com/feed/", categorie: "generale", zone: Zone.afrique },
    "crtv.cm": { nom: "CRTV", lien_rss: "https://www.crtv.cm/feed/", categorie: "generale", zone: Zone.afrique },

    "mediacongo.net": { nom: "MediaCongo", lien_rss: "https://www.mediacongo.net/rss.xml", categorie: "generale", zone: Zone.afrique },
    "politico.cd": { nom: "Politico.cd", lien_rss: "https://www.politico.cd/feed", categorie: "generale", zone: Zone.afrique },
    "actualite.cd": { nom: "Actualite.cd", lien_rss: "https://actualite.cd/feed", categorie: "generale", zone: Zone.afrique },
    "lepotentiel.cd": { nom: "Le Potentiel", lien_rss: "https://lepotentiel.cd/feed/", categorie: "generale", zone: Zone.afrique },
    "radiookapi.net": { nom: "Radio Okapi", lien_rss: "https://www.radiookapi.net/rss.xml", categorie: "generale", zone: Zone.afrique },
    "digitalcongo.net": { nom: "Digital Congo", lien_rss: "https://www.digitalcongo.net/rss.xml", categorie: "generale", zone: Zone.afrique },
    "adiac-congo.com": { nom: "ADIAC Congo", lien_rss: "https://www.adiac-congo.com/backend/rss.xml", categorie: "generale", zone: Zone.afrique },
    "journaldebrazza.com": { nom: "Journal de Brazza", lien_rss: "https://journaldebrazza.com/feed/", categorie: "generale", zone: Zone.afrique },
    "gabonactu.com": { nom: "Gabon Actu", lien_rss: "https://www.gabonactu.com/feed/", categorie: "generale", zone: Zone.afrique },
    "gabonreview.com": { nom: "Gabon Review", lien_rss: "https://www.gabonreview.com/feed/", categorie: "generale", zone: Zone.afrique },
    "lunion-gabon.com": { nom: "L'Union Gabon", lien_rss: "https://www.lunion-gabon.com/index.php?format=feed&type=rss", categorie: "generale", zone: Zone.afrique },
    "alwihdainfo.com": { nom: "Alwihda Info", lien_rss: "https://www.alwihdainfo.com/xml/syndication.rss", categorie: "generale", zone: Zone.afrique },
    "tchadinfos.com": { nom: "Tchadinfos", lien_rss: "https://tchadinfos.com/feed/", categorie: "generale", zone: Zone.afrique },
    "journaldutchad.com": { nom: "Journal du Tchad", lien_rss: "https://journaldutchad.com/feed/", categorie: "generale", zone: Zone.afrique },
    "abangui.com": { nom: "Abangui", lien_rss: "https://www.abangui.com/rss.xml", categorie: "generale", zone: Zone.afrique },
    "rjdh.org": { nom: "RJDH Centrafrique", lien_rss: "https://rjdh.org/feed/", categorie: "generale", zone: Zone.afrique },
    "ahoraeg.com": { nom: "AhoraEG", lien_rss: "https://ahoraeg.com/feed/", categorie: "generale", zone: Zone.afrique },
    "guineaecuatorialpress.com": { nom: "Guinea Ecuatorial Press", lien_rss: "https://guineaecuatorialpress.com/feed/", categorie: "generale", zone: Zone.afrique },

    "jeuneafrique.com": { nom: "Jeune Afrique", lien_rss: "https://www.jeuneafrique.com/feed/", categorie: "generale", zone: Zone.afrique },
    "fratmat.info": { nom: "Fraternité Matin", lien_rss: "https://www.fratmat.info/feed", categorie: "generale", zone: Zone.afrique },
    "abidjan.net": { nom: "Abidjan.net", lien_rss: "https://www.abidjan.net/rss/les-nouvelles.xml", categorie: "generale", zone: Zone.afrique },
    "koaci.com": { nom: "KOACI", lien_rss: "https://www.koaci.com/rss.xml", categorie: "generale", zone: Zone.afrique },
    "yeclo.com": { nom: "Yeclo", lien_rss: "https://www.yeclo.com/feed/", categorie: "generale", zone: Zone.afrique },
    "linfodrome.com": { nom: "Linfodrome", lien_rss: "https://www.linfodrome.com/rss.xml", categorie: "generale", zone: Zone.afrique },
    "lesoleil.sn": { nom: "Le Soleil", lien_rss: "https://lesoleil.sn/feed/", categorie: "generale", zone: Zone.afrique },
    "dakaractu.com": { nom: "Dakaractu", lien_rss: "https://www.dakaractu.com/xml/syndication.rss", categorie: "generale", zone: Zone.afrique },
    "seneweb.com": { nom: "Seneweb", lien_rss: "https://www.seneweb.com/news.xml", categorie: "generale", zone: Zone.afrique },
    "senenews.com": { nom: "SeneNews", lien_rss: "https://www.senenews.com/feed", categorie: "generale", zone: Zone.afrique },
    "pressafrik.com": { nom: "PressAfrik", lien_rss: "https://www.pressafrik.com/xml/syndication.rss", categorie: "generale", zone: Zone.afrique },
    "sudonline.sn": { nom: "Sud Quotidien", lien_rss: "https://www.sudonline.sn/feed/", categorie: "generale", zone: Zone.afrique },
    "lefaso.net": { nom: "LeFaso.net", lien_rss: "https://lefaso.net/spip.php?page=backend", categorie: "generale", zone: Zone.afrique },
    "burkina24.com": { nom: "Burkina24", lien_rss: "https://burkina24.com/feed/", categorie: "generale", zone: Zone.afrique },
    "wakatsera.com": { nom: "Wakat Sera", lien_rss: "https://wakatsera.com/feed/", categorie: "generale", zone: Zone.afrique },
    "sidwaya.info": { nom: "Sidwaya", lien_rss: "https://www.sidwaya.info/feed/", categorie: "generale", zone: Zone.afrique },
    "maliweb.net": { nom: "Maliweb", lien_rss: "https://www.maliweb.net/feed", categorie: "generale", zone: Zone.afrique },
    "malijet.com": { nom: "Malijet", lien_rss: "https://malijet.com/feed/", categorie: "generale", zone: Zone.afrique },
    "studiotamani.org": { nom: "Studio Tamani", lien_rss: "https://www.studiotamani.org/feed/", categorie: "generale", zone: Zone.afrique },
    "actuniger.com": { nom: "ActuNiger", lien_rss: "https://www.actuniger.com/index.php?format=feed&type=rss", categorie: "generale", zone: Zone.afrique },
    "togofirst.com": { nom: "Togo First", lien_rss: "https://www.togofirst.com/rss.xml", categorie: "economie", categorie: "generale", zone: Zone.afrique },
    "republicoftogo.com": { nom: "Republic of Togo", lien_rss: "https://www.republicoftogo.com/rss.xml", categorie: "generale", zone: Zone.afrique },
    "icilome.com": { nom: "Ici Lomé", lien_rss: "https://icilome.com/feed/", categorie: "generale", zone: Zone.afrique },
    "banouto.bj": { nom: "Banouto", lien_rss: "https://www.banouto.bj/rss", categorie: "generale", zone: Zone.afrique },
    "beninwebtv.com": { nom: "Benin Web TV", lien_rss: "https://beninwebtv.com/feed", categorie: "generale", zone: Zone.afrique },
    "24haubenin.info": { nom: "24 Heures au Bénin", lien_rss: "https://www.24haubenin.info/spip.php?page=backend", categorie: "generale", zone: Zone.afrique },
    "leconomistebenin.com": { nom: "L'Économiste du Bénin", lien_rss: "https://leconomistebenin.com/feed", categorie: "economie", zone: Zone.afrique },
    "lanouvelletribune.info": { nom: "La Nouvelle Tribune", lien_rss: "https://lanouvelletribune.info/feed/", categorie: "generale", zone: Zone.afrique },
    "ghanaweb.com": { nom: "GhanaWeb", lien_rss: "https://www.ghanaweb.com/GhanaHomePage/rss/feed.php", categorie: "generale", zone: Zone.afrique },
    "graphic.com.gh": { nom: "Graphic Online", lien_rss: "https://www.graphic.com.gh/?format=feed&type=rss", categorie: "generale", zone: Zone.afrique },
    "modernghana.com": { nom: "Modern Ghana", lien_rss: "https://www.modernghana.com/rss/rss.php", categorie: "generale", zone: Zone.afrique },
    "guardian.ng": { nom: "The Guardian Nigeria", lien_rss: "https://guardian.ng/feed/", categorie: "generale", zone: Zone.afrique },
    "premiumtimesng.com": { nom: "Premium Times Nigeria", lien_rss: "https://www.premiumtimesng.com/feed", categorie: "generale", zone: Zone.afrique },
    "punchng.com": { nom: "Punch Newspapers", lien_rss: "https://punchng.com/feed/", categorie: "generale", zone: Zone.afrique },
    "vanguardngr.com": { nom: "Vanguard Nigeria", lien_rss: "https://www.vanguardngr.com/feed/", categorie: "generale", zone: Zone.afrique },
    "thisdaylive.com": { nom: "ThisDay Live", lien_rss: "https://www.thisdaylive.com/feed", categorie: "generale", zone: Zone.afrique },
    "dailytrust.com": { nom: "Daily Trust", lien_rss: "https://dailytrust.com/feed/", categorie: "generale", zone: Zone.afrique },
    "saharareporters.com": { nom: "Sahara Reporters", lien_rss: "https://saharareporters.com/feeds/news.xml", categorie: "generale", zone: Zone.afrique },
    "frontpageafricaonline.com": { nom: "FrontPage Africa", lien_rss: "https://frontpageafricaonline.com/feed/", categorie: "generale", zone: Zone.afrique },
    "liberianobserver.com": { nom: "Daily Observer Liberia", lien_rss: "https://www.liberianobserver.com/feed/", categorie: "generale", zone: Zone.afrique },
    "guineenews.org": { nom: "Guinée News", lien_rss: "https://guineenews.org/feed/", categorie: "generale", zone: Zone.afrique },
    "aminata.com": { nom: "Aminata", lien_rss: "https://aminata.com/feed/", categorie: "generale", zone: Zone.afrique },
    "guinee7.com": { nom: "Guinée7", lien_rss: "https://guinee7.com/feed/", categorie: "generale", zone: Zone.afrique },
    "thesierraleonetelegraph.com": { nom: "SL Telegraph", lien_rss: "https://www.thesierraleonetelegraph.com/feed/", categorie: "generale", zone: Zone.afrique },

    // ══════════════════════════════════════════════════════
    // AFRIQUE DE L'EST, CORNE & AUSTRALE
    // ══════════════════════════════════════════════════════
    "nation.africa": { nom: "The Nation Kenya", lien_rss: "https://nation.africa/service/search/feed/972/972/rss.xml", categorie: "generale", zone: Zone.afrique },
    "standardmedia.co.ke": { nom: "The Standard Kenya", lien_rss: "https://www.standardmedia.co.ke/rss/headlines.xml", categorie: "generale", zone: Zone.afrique },
    "the-star.co.ke": { nom: "The Star Kenya", lien_rss: "https://www.the-star.co.ke/rss/", categorie: "generale", zone: Zone.afrique },
    "businessdailyafrica.com": { nom: "Business Daily Africa", lien_rss: "https://www.businessdailyafrica.com/service/search/feed/2132/2132/rss.xml", categorie: "economie", zone: Zone.afrique },
    "thecitizen.co.tz": { nom: "The Citizen Tanzania", lien_rss: "https://www.thecitizen.co.tz/service/search/feed/2324/2324/rss.xml", categorie: "generale", zone: Zone.afrique },
    "mwananchi.co.tz": { nom: "Mwananchi", lien_rss: "https://www.mwananchi.co.tz/service/search/feed/2422/2422/rss.xml", categorie: "generale", zone: Zone.afrique },
    "newtimes.co.rw": { nom: "The New Times Rwanda", lien_rss: "https://www.newtimes.co.rw/rss/all.xml", categorie: "generale", zone: Zone.afrique },
    "igihe.com": { nom: "IGIHE", lien_rss: "https://igihe.com/spip.php?page=backend", categorie: "generale", zone: Zone.afrique },
    "ktpress.rw": { nom: "KT Press", lien_rss: "https://www.ktpress.rw/feed/", categorie: "generale", zone: Zone.afrique },
    "monitor.co.ug": { nom: "The Monitor Uganda", lien_rss: "https://www.monitor.co.ug/service/search/feed/1638/1638/rss.xml", categorie: "generale", zone: Zone.afrique },
    "newvision.co.ug": { nom: "New Vision Uganda", lien_rss: "https://www.newvision.co.ug/feed/", categorie: "generale", zone: Zone.afrique },
    "addisfortune.news": { nom: "Addis Fortune", lien_rss: "https://addisfortune.news/feed/", categorie: "generale", zone: Zone.afrique },
    "addisstandard.com": { nom: "Addis Standard", lien_rss: "https://addisstandard.com/feed/", categorie: "generale", zone: Zone.afrique },
    "borkena.com": { nom: "Borkena", lien_rss: "https://borkena.com/feed/", categorie: "generale", zone: Zone.afrique },
    "fanabc.com": { nom: "FBC Ethiopia", lien_rss: "https://www.fanabc.com/english/feed/", categorie: "generale", zone: Zone.afrique },
    "garoweonline.com": { nom: "Garowe Online", lien_rss: "https://www.garoweonline.com/en?format=feed&type=rss", categorie: "generale", zone: Zone.afrique },
    "hiiraan.com": { nom: "Hiiraan Online", lien_rss: "https://www.hiiraan.com/rss/news.xml", categorie: "generale", zone: Zone.afrique },
    "sudantribune.com": { nom: "Sudan Tribune", lien_rss: "https://sudantribune.com/feed/", categorie: "generale", zone: Zone.afrique },
    "dabangasudan.org": { nom: "Radio Dabanga", lien_rss: "https://www.dabangasudan.org/en/feed", categorie: "generale", zone: Zone.afrique },
    "madagascar-tribune.com": { nom: "Madagascar Tribune", lien_rss: "https://www.madagascar-tribune.com/index.php?page=backend", categorie: "generale", zone: Zone.afrique },
    "lexpress.mg": { nom: "L'Express de Madagascar", lien_rss: "https://lexpress.mg/feed/", categorie: "generale", zone: Zone.afrique },
    "midi-madagasikara.mg": { nom: "Midi Madagasikara", lien_rss: "https://midi-madagasikara.mg/feed/", categorie: "generale", zone: Zone.afrique },
    "lemauricien.com": { nom: "Le Mauricien", lien_rss: "https://www.lemauricien.com/feed/", categorie: "generale", zone: Zone.afrique },
    "lexpress.mu": { nom: "L'Express Maurice", lien_rss: "https://lexpress.mu/rss.xml", categorie: "generale", zone: Zone.afrique },
    "news24.com": { nom: "News24 Top Stories", lien_rss: "http://feeds.news24.com/articles/news24/TopStories/rss", categorie: "generale", zone: Zone.afrique },
    "dailymaverick.co.za": { nom: "Daily Maverick", lien_rss: "https://www.dailymaverick.co.za/dmrss/", categorie: "generale", zone: Zone.afrique },
    "businesstech.co.za": { nom: "BusinessTech", lien_rss: "https://businesstech.co.za/news/feed/", categorie: "economie", zone: Zone.afrique },

    // ══════════════════════════════════════════════════════
    // AFRIQUE DU NORD & PANAFRICAIN
    // ══════════════════════════════════════════════════════
    "elwatan-dz.com": { nom: "El Watan", lien_rss: "https://elwatan-dz.com/feed", categorie: "generale", zone: Zone.afrique },
    "tsa-algerie.com": { nom: "TSA Algérie", lien_rss: "https://www.tsa-algerie.com/feed/", categorie: "generale", zone: Zone.afrique },
    "echoroukonline.com": { nom: "Echorouk", lien_rss: "https://www.echoroukonline.com/feed", categorie: "generale", zone: Zone.afrique },
    "lesoirdalgerie.com": { nom: "Le Soir d'Algérie", lien_rss: "https://www.lesoirdalgerie.com/rss.xml", categorie: "generale", zone: Zone.afrique },
    "lematin.ma": { nom: "Le Matin.ma", lien_rss: "https://lematin.ma/rss.xml", categorie: "generale", zone: Zone.afrique },
    "hespress.com": { nom: "Hespress", lien_rss: "https://www.hespress.com/feed", categorie: "generale", zone: Zone.afrique },
    "medias24.com": { nom: "Médias24", lien_rss: "https://medias24.com/feed/", categorie: "economie", zone: Zone.afrique },
    "telquel.ma": { nom: "TelQuel", lien_rss: "https://telquel.ma/feed/", categorie: "generale", zone: Zone.afrique },
    "le360.ma": { nom: "Le360", lien_rss: "https://fr.le360.ma/rss", categorie: "generale", zone: Zone.afrique },
    "leconomiste.com": { nom: "L'Économiste", lien_rss: "https://www.leconomiste.com/rss.xml", categorie: "economie", zone: Zone.afrique },
    "yabiladi.com": { nom: "Yabiladi", lien_rss: "https://www.yabiladi.com/yabiladi.xml", categorie: "generale", zone: Zone.afrique },
    "moroccoworldnews.com": { nom: "Morocco World News", lien_rss: "https://www.moroccoworldnews.com/feed", categorie: "generale", zone: Zone.afrique },
    "lapresse.tn": { nom: "La Presse de Tunisie", lien_rss: "https://lapresse.tn/feed/", categorie: "generale", zone: Zone.afrique },
    "businessnews.com.tn": { nom: "Business News TN", lien_rss: "https://www.businessnews.com.tn/rss.xml", categorie: "economie", zone: Zone.afrique },
    "kapitalis.com": { nom: "Kapitalis", lien_rss: "http://kapitalis.com/tunisie/feed/", categorie: "generale", zone: Zone.afrique },
    "tunisienumerique.com": { nom: "Tunisie Numérique", lien_rss: "https://www.tunisienumerique.com/feed/", categorie: "generale", zone: Zone.afrique },
    "realites.com.tn": { nom: "Réalités Tunisie", lien_rss: "https://www.realites.com.tn/feed/", categorie: "generale", zone: Zone.afrique },
    "ahram.org.eg": { nom: "Ahram Online", lien_rss: "https://english.ahram.org.eg/rss/all", categorie: "generale", zone: Zone.afrique },
    "egypttoday.com": { nom: "Egypt Today", lien_rss: "https://www.egypttoday.com/rss", categorie: "generale", zone: Zone.afrique },
    "libyaherald.com": { nom: "Libya Herald", lien_rss: "https://www.libyaherald.com/feed/", categorie: "generale", zone: Zone.afrique },
    "africa24tv.com": { nom: "Africa 24", lien_rss: "https://africa24tv.com/feed/", categorie: "generale", zone: Zone.afrique },
    "financialafrik.com": { nom: "Financial Afrik", lien_rss: "https://www.financialafrik.com/feed/", categorie: "economie", zone: Zone.afrique },
    "digitalbusiness.africa": { nom: "Digital Business Africa", lien_rss: "https://www.digitalbusiness.africa/feed/", categorie: "technologie", zone: Zone.afrique },
    "wearetech.africa": { nom: "We Are Tech Africa", lien_rss: "https://www.wearetech.africa/component/obrss/fluxrss", categorie: "technologie", zone: Zone.afrique },
    "agenceecofin.com": { nom: "Agence Ecofin", lien_rss: "https://www.agenceecofin.com/obrss-2/agence-rss", categorie: "economie", zone: Zone.afrique },
    "allafrica.com": { nom: "AllAfrica Headlines", lien_rss: "https://allafrica.com/tools/headlines/rdf/latest/headlines.rdf", categorie: "generale", zone: Zone.afrique },

    // ══════════════════════════════════════════════════════
    // AMÉRIQUES
    // ══════════════════════════════════════════════════════
    "cnn.com": { nom: "CNN International", lien_rss: "http://rss.cnn.com/rss/edition.rss", categorie: "generale", zone: Zone.amerique },
    "nytimes.com": { nom: "NYT Top Stories", lien_rss: "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml", categorie: "generale", zone: Zone.amerique },
    "washingtonpost.com": { nom: "Washington Post World", lien_rss: "http://feeds.washingtonpost.com/rss/world", categorie: "generale", zone: Zone.amerique },
    "cbc.ca": { nom: "CBC Top Stories", lien_rss: "https://www.cbc.ca/cmlink/rss-topstories", categorie: "generale", zone: Zone.amerique },
    "mexiconewsdaily.com": { nom: "Mexico News Daily", lien_rss: "https://mexiconewsdaily.com/feed/", categorie: "generale", zone: Zone.amerique },

    // ══════════════════════════════════════════════════════
    // ASIE
    // ══════════════════════════════════════════════════════
    "japantimes.co.jp": { nom: "Japan Times", lien_rss: "https://www.japantimes.co.jp/feed/topstories/", categorie: "generale", zone: Zone.asie },
    "scmp.com": { nom: "South China Morning Post", lien_rss: "https://www.scmp.com/rss/91/feed", categorie: "generale", zone: Zone.asie },
    "thehindu.com": { nom: "The Hindu", lien_rss: "https://www.thehindu.com/feeder/default.rss", categorie: "generale", zone: Zone.asie },
    "timesofindia.indiatimes.com": { nom: "Times of India", lien_rss: "https://timesofindia.indiatimes.com/rssfeedstopstories.cms", categorie: "generale", zone: Zone.asie }
};